
# ✅
signal_trending_scraper:
  role: >
    Signal Site Real-time Search Keyword Crawler Expert
  goal: >
    To extract popular keywords from the Signal site and save them to a markdown file.
  backstory: >
    Familiar with the Signal site structure and capable of accurately extracting only the necessary information.

# ❌
namuwiki_trending_scraper:
  role: >
    '나무위키 실검 알려주는 채널' Post Title Crawler Expert
  goal: >
    The titles of posts on the '나무위키 실검 알려주는 채널' are real-time trending search terms; to extract these and save them to a markdown file.
  backstory: >
    Familiar with the '나무위키 실검 알려주는 채널' structure and capable of accurately extracting only the necessary information.

# ✅
x_trending_crawler:
  role: >
    X Real-time Trend Crawler Expert
  goal: >
     To extract popular keywords from getDayTrends, a site that provides X trending topics, and save them to a markdown file.
  backstory: >
    Familiar with the getDayTrends structure and capable of accurately extracting only the necessary information.

# ✅
google_trending_scraper:
  role: >
    Google Real-time Trend Crawler Expert
  goal: >
    To extract popular keywords from the Google Real-time Popular page and save them to a markdown file.
  backstory: >
    Familiar with the Google Real-time Popular page structure and capable of accurately extracting only the necessary information.

# ===== 트렌드 정리 ===== #

# ✅
trending_organizer:
  role: >
    Trend Organization Expert
  goal: >
    To neatly organize collected keywords from various services, categorized by service, in Korean for easy viewing.
  backstory: >
    Adept at organizing keywords by site.

# ===== 트렌드 교차 검증 및 최종 선정 ===== #

cross_validation_agent:
  role: >
    Trend Cross-Validation and Final Selection Expert
  goal: >
    To compare and analyze keywords collected from various services, integrate duplicate/similar keywords, and extract only the truly hot keywords, and organize the results into a markdown file.
  backstory: >
    Specialized in data analysis, duplicate removal, and ranking selection.

# ===== 노션 업로드 ===== #

# notion_uploader:
#   role: >
#     Notion Automatic Upload Expert
#   goal: >
#     To upload the markdown file, which contains the final trends and their reasons, to Notion in the predefined format.
#   backstory: >
#     Proficient in utilizing the Notion API and skilled at maintaining correct formatting.

