create_meme_tokens:
  description: >
    Read 'output/final.md', which contains the top 3 trending keywords and their explanations.
    For each keyword, generate meme token information including:
    - Name
    - Symbol (3-5 uppercase letters)
    - Description (fun, meme-based explanation)
    - Image prompt: Generate a highly detailed, evocative, and strategic description for visual generation, specifically tailored for a meme token.
      This image prompt MUST strictly adhere to the following principles to ensure it is iconic, viral-ready, and high-quality:

      **[Image Prompt Generation Principles for Meme Tokens]**

      1.  **Be ICONIC & MEMORABLE:** Describe a visual that is instantly recognizable, distinct, and designed for viral sharing. Avoid generic poses or common elements unless stylized uniquely. Aim for a "snapshot" moment that encapsulates the trend.
      2.  **Be DEEPLY SYMBOLIC & THEMATIC:** Clearly translate the "Why it's trending" explanation into a powerful visual metaphor or direct representation. Every element should contribute to the core message (e.g., devotion, new chapter, impactful change).
      3.  **Be VISUALLY STRIKING & ARTISTIC:** Use vivid, descriptive language for the aesthetic. Specify the **exact artistic style** (e.g., 'photorealistic', 'stylized digital illustration', 'pop art', 'hyper-realistic cinematic render') that best suits the meme's tone. Describe lighting (e.g., 'golden hour glow', 'neon reflections', 'dramatic backlighting'), color palette (e.g., 'vibrant and bold', 'soft ethereal pastels', 'contrasting team colors'), and overall atmosphere (e.g., 'triumphant', 'serene', 'energetic').
      4.  **Be CLEAN & FOCUSED:** The main subject must be the unambiguous focal point. Describe a background that is either minimalist, symbolically relevant, or intentionally blurred to enhance focus. Avoid clutter.
      5.  **Be SPECIFIC & DETAILED:** Provide granular details for the subject's **expression, pose, specific objects held or interacted with, clothing details, and any unique visual effects.** (e.g., not just 'military uniform' but 'impeccably tailored South Korean military uniform with polished boots').
      6.  **Ensure SQUARE RATIO:** Explicitly state "Square ratio (1:1)" at the end of the prompt for optimal token display.
      7.  **Include QUALITY CONTROL (Negative Prompt):** ALWAYS end the prompt with a comprehensive negative prompt to exclude undesirable elements (e.g., `Negative prompt: blurry, text, low quality, deformed, bad anatomy, ugly, generic, watermark, oversaturated, unrealistic`).

      **[Example of a High-Quality Image Prompt for a Meme Token]**
      * "An iconic, striking full-body portrait of Cha Eun-woo, conveying a dignified and hopeful military enlistment. He stands upright and poised in a brand-new, impeccably tailored South Korean military uniform with polished boots and a neat, short military haircut. His expression is confident and serene, featuring his characteristic gentle smile that carries a subtle sense of resolve and a promise of return. He is positioned against a clean, minimalist background of a bright, clear sky, with subtle, inspiring light rays radiating from behind him, symbolizing a new chapter and national pride. The overall image exudes a sense of honor, anticipation, and iconic visual presence, perfect for a viral meme token. This is a photorealistic, high-detail image with a powerful, clean aesthetic. Square ratio (1:1). Negative prompt: blurry, text, low quality, cartoon, generic, overly stern, sad, messy uniform."

    Save all token information into a markdown file 'output/meme_tokens.md' with clear headings for each.

  expected_output: >
    A markdown file 'output/meme_tokens.md' with 3 meme tokens, each with name, symbol, description, and image prompt.
  agent: meme_token_creator


generate_meme_token_images:
  description: >
    Read 'output/meme_tokens.md' and extract the image prompt for each token.
    Generate one image per token using the prompt, and save as PNG files in 'output/images/{symbol}.png'.

  expected_output: >
    3 images stored in the 'output/images' folder, named by token symbol (e.g., CWJ.png, TRDZ.png).
  agent: meme_token_image_generator
