generate_token_metadata:
  description: >
    Read 'output/final.md', which contains the trending keyword and its explanation.
    Given a trend keyword and a short explanation, create meme token metadata.
    This includes a creative name, an all-uppercase symbol (3–6 letters), and a brief, witty description 
    connecting the trend to meme culture.
    The name should be catchy or playful, and the description should highlight why this token exists.
    After generating the metadata, call the File Writer Tool to save the result as a JSON file named 'output/metadata/{SYMBOL}.json'.
    You must include the correct file name based on the symbol.
  expected_output: >
    A JSON file output/metadata/{symbol}.json
    A JSON object with the following structure:
    {
      "name": "<Token Name>",
      "symbol": "<SYMBOL>",
      "description": "<Witty, concise token description>"
    }

  agent: token_meta_generator



visual_prompt_generator:
  role: >
    Visual Prompt Engineer
  goal: >
    Generate visually striking, context-aware prompts for AI image generation models based on trending topics. Prompts should be memorable, symbolic when appropriate, and accurate—especially when real people are involved—while adhering to strong stylistic and compositional principles.
  backstory: >
    This agent converts real-time cultural, political, or entertainment trends into high-quality visual prompts. It guides image models like DALL·E or Midjourney using artistic direction, visual symbolism, and narrative clarity to produce viral, iconic, and coherent imagery. It avoids ambiguous metaphor or overused tropes unless they are core to the trend’s meaning and impact.

generate_image_prompt:
  description: >
    Given a trend keyword and its explanation, write a vivid and specific image generation prompt suitable for DALL·E, Midjourney, or other visual AI models.

    The prompt must follow these core principles:

    1. **ICONIC & MEMORABLE**: Describe a unique, snapshot-worthy visual that instantly conveys the subject’s relevance. Avoid generic compositions; focus on expressive moments, symbolic gestures, or dynamic framing.

    2. **SYMBOLIC & THEMATIC**: Translate the “Why it’s trending” into meaningful visual metaphors or direct representations. Every element should reinforce the core theme or emotional resonance. Symbolic elements should only be used when directly relevant to the subject.

    3. **STYLISTIC PRECISION**: Clearly state the desired artistic style (e.g., “photo-realistic”, “hyper-realistic cinematic render”, “digital pop-art”). Include lighting details (e.g., “golden hour glow”, “dramatic spotlight”), color palette (e.g., “team colors”, “ethereal pastels”), and overall atmosphere (e.g., “triumphant”, “reflective”, “urgent”).  
       While cartoon or caricature styles are technically possible, **they should be avoided unless stylistically essential** to the trend's tone or audience.

    4. **FOCUSED COMPOSITION**: Keep the main subject as the unambiguous focal point. Backgrounds should be clean, blurred, or symbolically relevant to enhance clarity.

    5. **SPECIFIC VISUAL DETAILING**: Describe facial expression, posture, clothing details, props, and any relevant actions. Avoid vague descriptors.

    6. **TECHNICAL CONTROL**:
       - Append this negative prompt to filter undesirable outputs:  
         `Negative prompt: blurry, text, low quality, deformed, bad anatomy, generic, watermark, oversaturated, unrealistic`

    7. **REAL-PERSON HANDLING**:
       - If the trend involves a real person, their **full name must appear** in the prompt.
       - Describe them in detail: age range, hairstyle, facial features, clothing, typical context (e.g., stadium, press conference), and any signature accessories or gestures.
       - **Do not use cartoon, stylized, caricature, or meme art styles** when depicting real people. Only use **photo-realistic**, **cinematic**, or **press-style** renderings to maintain likeness and respect.

    Additional guideline:  
    Use grounded and literal imagery. Avoid metaphorical or symbolic language unless it is directly relevant to the trend itself. Make the scene visually intentional by specifying the setting, background elements, mood, lighting, and overall atmosphere to create a vivid and unambiguous mental image.

  expected_output: >
    A txt file output/prompts/{symbol}.txt
    A plain-text image generation prompt.
    The output should be a single English paragraph suitable for guiding an AI image generation model.
    Do not wrap it in Markdown or JSON. Save this file in output/prompts.

  agent: visual_prompt_generator


# generate_meme_token_images:
#   description: >
#     Read 'output/meme_tokens.md' and extract the image prompt and symbol for each meme token listed.
#     For each token explicitly found in the file, generate exactly one image using the corresponding prompt.
#     Save each image as a PNG file in 'output/images/{symbol}.png'.
#     Do NOT invent, infer, or hallucinate any tokens or prompts not explicitly written in the file.

#   expected_output: >
#     One PNG image per token listed in the markdown file.
#     Each image should be saved to the 'output/images' folder using the token symbol as the filename (e.g., CWJT.png).
#     The total number of images must match the number of tokens in the file — no more, no less.

#   agent: meme_token_image_generator