layout_patterns:
  - name: "Classic Centered"
    hero_alignment: "center"
    image_position: "top"
    section_order: ["hero", "about", "tokenomics", "community"]
    font_style: "Orbitron"
    animation: "pulse"
    button_style: "solid-center"

  - name: "Left-Heavy Bold"
    hero_alignment: "left"
    image_position: "left"
    section_order: ["hero", "tokenomics", "about", "community"]
    font_style: "Bungee"
    animation: "bounce"
    button_style: "left-outline"

  - name: "ZigZag Dynamic"
    hero_alignment: "right"
    image_position: "right"
    section_order: ["hero", "community", "about", "tokenomics"]
    font_style: "Comic Neue"
    animation: "shake"
    button_style: "right-glow"

  - name: "Minimal Meme"
    hero_alignment: "center"
    image_position: "top"
    section_order: ["hero", "about", "community", "tokenomics"]
    font_style: "Quicksand"
    animation: "none"
    button_style: "ghost-center"

  - name: "Pop-Art Party"
    hero_alignment: "left"
    image_position: "right"
    section_order: ["hero", "about", "tokenomics", "community"]
    font_style: "Press Start 2P"
    animation: "bounce"
    button_style: "rainbow-border"

  - name: "Split Screen Chaos"
    hero_alignment: "left"
    image_position: "right"
    section_order: ["hero", "tokenomics", "community", "about"]
    font_style: "Rubik Doodle Shadow"
    animation: "wiggle"
    button_style: "split-gradient"

  - name: "Retro Arcade"
    hero_alignment: "center"
    image_position: "top"
    section_order: ["hero", "about", "tokenomics", "community"]
    font_style: "VT323"
    animation: "flicker"
    button_style: "pixelated"

  - name: "Meme Matrix"
    hero_alignment: "right"
    image_position: "left"
    section_order: ["hero", "community", "tokenomics", "about"]
    font_style: "Source Code Pro"
    animation: "glitch"
    button_style: "matrix-hack"

  - name: "Floating Island"
    hero_alignment: "center"
    image_position: "top"
    section_order: ["hero", "about", "tokenomics", "community"]
    font_style: "Fredoka One"
    animation: "float"
    button_style: "neon-hover"

  - name: "Extreme Meme Machine"
    hero_alignment: "left"
    image_position: "right"
    section_order: ["hero", "about", "community", "tokenomics"]
    font_style: "Carter One"
    animation: "jiggle"
    button_style: "exploding"
